@ECHO OFF

set username=thatoranzhevyy
set year=2000
set repositori=twentieth-century

MKDIR %username%
cd %username%

git init
echo %repositori% - Generated by https://github.com/thatoranzhevyy/twentieth-century >README.md
git add .
git commit -m "commited from %year%" --date="%year%-12-31T12:00:00+0300"

git remote add origin "https://github.com/%username%/%repositori%.git"
git branch -M master
git push -u origin master -f
cd ..
rd /s /q %username%
PAUSE
